### ISSUE TITLE
Generate Mountain Top cups from OSM?

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#107]
@dspreitz 

Indepdently of your current merge request:

What if we could generate a list of the mountain peaks with OSM?:

Relevant tags:
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeak
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dsaddle

I'm trying to prevent it to be necessary to care for this data by hand.

**Comment by alnitac** [comment]
Hi,
Nice idea. I would like to give it a try for the Pyrénées where i like to fly and hike.

**Comment by SteveBaum** [comment]
Dear folks,

I just generated mountain peak lists in SeeYou CUP format for several regions of Europe and of entire New Zealand. You can download them either under [http://zirbitzkogel.at/blog/en/2021/06/04/peaks-mountain-peaks-in-seeyou-cup-format-for-xcsoar/](http://zirbitzkogel.at/blog/en/2021/06/04/peaks-mountain-peaks-in-seeyou-cup-format-for-xcsoar/) (English explanation) or [http://zirbitzkogel.at/blog/2021/06/03/gipfel-berggipfel-im-seeyou-cup-format-fuer-xcsoar/](http://zirbitzkogel.at/blog/2021/06/03/gipfel-berggipfel-im-seeyou-cup-format-fuer-xcsoar/) (German explanation, "Deutsche Erklärung").

If you also have interest in different regions of the world, let me now.

Regards,

Stefan

**Comment by mlep** [comment]
Great!
Maybe a good repository could be https://soaringweb.org/ ?

**Comment by mlep** [comment]
@SteveBaum  What is the character encoding of the cup files?

**Comment by SteveBaum** [comment]
> 
> 
> @SteveBaum What is the character encoding of the cup files?

It's ANSI and the line ends with CR + LF.

**Comment by mlep** [comment]
OK for the CR + LF.

About ANSI, do you mean Windows-1252? (see https://en.wikipedia.org/wiki/ANSI_character_set)
In fact, I have not found a suitable encoding to import, and the file command is confused too:
````
$ file mountain_peaks_ALPS_extended.cup
mountain_peaks_ALPS_extended.cup: Non-ISO extended-ASCII text, with CRLF line terminators
````

Note, in the file mountain_peaks_ALPS_extended.cup:
- the second line (HALS) contains "double double quotes" :` ""HALS""`
- `"Viewpoint  "Orlove Glave""`, `"Moränenhïgel "Peterwirtshügel""` and `"Auf der "Ebb""`  are malformed.

Cheers.

**Comment by SteveBaum** [comment]
> 
> 
> OK for the CR + LF.
> 
> About ANSI, do you mean Windows-1252? (see https://en.wikipedia.org/wiki/ANSI_character_set)
> In fact, I have not found a suitable encoding to import, and the file command is confused too:
> 
> ```
> $ file mountain_peaks_ALPS_extended.cup
> mountain_peaks_ALPS_extended.cup: Non-ISO extended-ASCII text, with CRLF line terminators
> ```
> 
> Note, in the file mountain_peaks_ALPS_extended.cup:
> 
>     * the second line (HALS) contains "double double quotes" :` ""HALS""`
> 
>     * `"Viewpoint  "Orlove Glave""`, `"Moränenhïgel "Peterwirtshügel""` and `"Auf der "Ebb""`  are malformed.
> 
> 
> Cheers.

The paricular encoding should be ANSI ISO 8859-1 (West European).  I will update my software so that UTF8 files are generated. Meanwhile, you could try to convert to UTF8 using Notpad++ on Windows. 

Regarding "double double quotes"): Is this a problem causing XCSoar or other software to crash? I haven't observed a crash so far on XCSoar running under Windows 10 and on an older Andruid phone. There is more danger, that older devices cannot handle the large file size. Anyhow, thanks for the hint. The next software version will replace any quotes with empty spaces.

The point is, that so far I read the mountain names from OpenStreetMap (OSM) more or less as they are. Sometimes people putting names in quotes, brackets and so on. What's right, what`s wrong? 

Also the peak and, thus, the waypoint names are not unique. They are also not unique in OSM. 

However, there are also characters in OSM data my software wasn't able to read. These unknown characters I replaced with a "?" (see for instance at the end of the mountain_peaks_ALPS_extended.cup file where a number of files with unreadable characters are listed). 

The alternative would be to exclude peaks with invalid names from the list. However, I decided to use all peak nodes from OSM. 

In the end, by using "unverifiied" OSM data as input, you never can be sure if it is true peak or just a molehill :-)

Regards,

Stefan

**Comment by mlep** [comment]
Thanks for your prompt reply. 
I have not tried the file in XCSoar (yet). I processed it to extract the area relevant to me.

Thank you for sharing your work with the community!

**Comment by lordfolken** [comment]
for reference: http://download.naviter.com/docs/CUP-file-format-description.pdf the cup file "standard".
Please convert to UTF-8. ISO-8859-1 only allows for West European charsets, so once you move out of that region things start to break. (baltic states for example, or aisan..)

Double double quotes are not a problem in a csv file, there might be parsers other than our own that cannot deal with that. Aslong as there are no excessive commas. Please check the fields for commas. To be clean use literal quotes for the fields:
```csv
'Viewpoint "Orlove Glave"','Moränenhïgel "Peterwirtshügel"','Auf der "Ebb"'
```

For easy integration into XCSoar we could put them into the download manager:
 - Please convert the files to UTF-8 Unicode
 - Fix the fields
 - Make them available directly without zipping them (your server has most likely gzip inline compression)
 - You can add comments from liesmich at the top of the files prefixed with #
 - tell me the urls or provide a pr, and i can add them to the https://github.com/XCSoar/xcsoar-data-repository

**Comment by lordfolken** [comment]
@SteveBaum would you mind opensourcing your script? My strategy is to be able to derive all data from foreign sources.

**Comment by llauner** [comment]
See #370 
Data is coming from http://zirbitzkogel.at/blog/en/2021/06/04/peaks-mountain-peaks-in-seeyou-cup-format-for-xcsoar/ which is coming from OSM
