### ISSUE TITLE
Deprecate this data

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-content#13]
Here we are maintaining Data, which is not something we should be doing from an XCSoar project perspective. 

This repo is an emergency solution, as the welt2000 team has decided to stop supporting their file. The philosophy was that http://openflightmaps.org/ would be taking over all the countries that welt2000 supports. 

However OFM does not maintain gliding turnpoints or outlanding sites. Neither are there metric charts available and the charts available do not display gliding specific airspace. (At least Switzerland). 
In addtion all their data is zipped, so we cannot link directly from xcsoar to that site. This is something I discussed with them in spring 2018, they stated that they would change that, but sofar no change is visible.

OpenAIP also does also not feature turnpoints or outlanding sites. In addition there is the liscensing issue which prohibits commercial use.

Which brings us to the soaringweb.org turnpoint exchange.  There are resources there, but they are decades old and unmaintained.

So in the end, what we currently have here is the most clean / up2date dataset. 

The future strategy could possibly be: 
 - Remove airfields from the files (as long as they are in other sources) 
 - Merge external data, such as OFM or openaip data.

**Comment by rawtaz** [comment]
I see your point, but at the same time it makes sense to have a source of data that is under our control, so we know it won't go away all of a sudden and that it has clean, usable data in it.

Unless there's a clear alternative out there, I think we should keep it, and if need be look into the merging of data you mention. That is, some scripts that pull in and merge data from other sources, but still into our own repository so that we have it nicely contained.

I've heard numerous times how cool people think it is when they can just hit a button in XCSoar and select data to download - Everyone I know who knows about it thinks it's awesome :)

**Comment by hor63** [comment]
I guess we are mostly on our own here.
I am sitting down in the evenings now and grinding systematically through the German airports for the radio channel updates, but also general cleanup, and adding ICAO codes.
Really tedious because the DFS frequency list is still woefully incomplete. So looking up OpenAIP and the DFS AIP (which does not list non-ICAO airfields :( ) and looking for websites of the operators.

Kai

**Comment by lordfolken** [comment]
@hor63 thank you for doing this.

Please also have a look at horst's data: 
https://www.how2soar.de/index.php/downloads-navi-daten-und-anderes/navi-daten/download-von-navi-daten

He has been cultivating a process with quality checks and reviews of coordinates via google earth. HIs process is described on the homepage. I think his coordinates are quite accurate, but airfield data might not be up to date, especially due to the frequency changes.

**Comment by hor63** [comment]
I check coordinates for almost all airfields, particularly the more obscure ones. They are all spot on so far.
I am checking most landing fields in Google Earth. Some surprises there. Some of them are completely covered with solar panels now. Ugh. I am removing these of course.
I will attach a list of the maor changes at the end, including deleted landing fields, fields with maor changes, and fields with no frequency, the majority of them UL fields.

Kai

**Comment by rawtaz** [comment]
I suggest that we close this issue. I don't see how there's any other place to get the same quality data as this repository provides, and besides making sure it's in a somewhat controlled fashion we also have control over what type of data it includes. Even if we were to find some other resource, it's like any other system, it may meet the majority of our use case, but lack the rest. I personally think that we should simply keep this repo. If other alternatives pop up with time, we can revisit. But there's little point in keeping this issue open.

**Comment by lordfolken** [comment]
There is some thing we could get from other sources: 
  * airfields: openaip (we need to talk to them about including their data)
  * outlandingfields: landewiesen.streckenflug.at (we also need to talk with them)
  * mountain tops / passes, churches, train stations: from OSM
  * thermal
