### ISSUE TITLE
Description field: Flugplatz --> Airfield?

### ISSUE THREAD

**Issue by mlep** [XCSoar/xcsoar-data-content#83]
Currently, the cup files contains descriptions in German.
Shall they be translated into English?
For example, does "Flugplatz" should be converted into "Airfield"?

**Comment by lordfolken** [comment]
The last field is the comment field which is a text field that is show in the "Description" field of the waypoint. The original source for this data was the welt2000 file. I think they included this redundant information due to the fact, that old navigation systems didn't clearly show that the waypoint was an airport.

The waypoint type (Field 7) shows that its an aiport: there are 3 values in existence:
2 Airfield with grass surface runway
4 Gliding airfield
5 Airfield with solid surface runway

The CUP format is defined here: http://download.naviter.com/docs/CUP-file-format-description.pdf

So hence, if you could actually remove the "Flugplatz" description from all files, you'd do the world a service. :-)

**Comment by mlep** [comment]
Thank you for the details about the waypoints and the link to the format description.
I have started to clean the airfields for France (PR  #84). In the process, I will remove the comment fields. But for now, I will keep them, because they are useful for a first sorting.

**Comment by lordfolken** [comment]
@melp can you close this?
